server:
  port: 9873
spring:
  application:
    name: sip-config
  cloud:
    config:
      server:
        git:
          # 配置git仓库的地址
          uri: https://github.com/guwoow/sip-config
          # git仓库地址下的相对地址，可以配置多个，用,分割。
          search-paths: config-repository
          # git仓库的账号（私有库必填）
          username:
          # git仓库的密码（私有库必填）
          password:
      # 配置git仓库的分支
      label: master